export enum ProductStatus {
  PAUSE = "PAUSE",
  PROCESS = "PROCESS",
  SOLD_OUT = "SOLD_OUT",
  DELIVERED = "DELIVERED",
}

export enum ProductCategory {
  PHONE = "PHONE",
  LAPTOP = "LAPTOP",
  TABLET = "TABLET",
  CPU = "CPU",
  GPU = "GPU",
  RAM = "RAM",
  MOTHERBOARD = "MOTHERBOARD",
  STORAGE = "STORAGE",
  MONITOR = "MONITOR",
  KEYBOARD = "KEYBOARD",
  MOUSE = "MOUSE",
  HEADSET = "HEADSET",
  PSU = "PSU",
  CASE = "CASE",
}

export enum ProductBrand {
  ASUS = "ASUS",
  MSI = "MSI",
  SAMSUNG = "SAMSUNG",
  APPLE = "APPLE",
  AMD = "AMD",
  LOGITECH = "LOGITECH",
  CORSAIR = "CORSAIR",
  LENOVO = "LENOVO",
  ACER = "ACER",
  INTEL = "INTEL",
  GIGABYTE = "GIGABYTE",
  KINGSTON = "KINGSTON",
  GSKILL = "GSKILL",
  SEASONIC = "SEASONIC",
  BE_QUIET = "BE_QUIET",
  NZXT = "NZXT",
  LIAN_LI = "LIAN_LI",
  FRACTAL = "FRACTAL",
}
